### PR TITLE
Add more field

### PR DESCRIPTION
**Pull request by O-S-K**
- Add push
- Add shake
- Add loops

- Update rotation add mode rotation

### CODE REVIEW

**Comment by Mr-sB** [comment]
It seems that some important classes have been deleted, it doesn't work.

**Comment by O-S-K** [comment]
I just added the fields above (I just updated the description), can you tell me what error you got?

**Comment by O-S-K** [comment]
and i think you can add editor to preview editor to reduce testing time

**Comment by Mr-sB** [comment]
> 我刚刚添加了上面的字段（我刚刚更新了描述），你能告诉我你遇到了什么错误吗？

image
UIDOTween and SingleTween are missing.

**Comment by Mr-sB** [comment]
> 我认为你可以将编辑器添加到预览编辑器中以减少测试时间

I tried to add this feature one year ago, but i got stuck in some problems.  In the end, i gave up. : (

**Comment by O-S-K** [comment]
i forgot commit scripts file

**Pull request closed without merging**
